### ISSUE TITLE
官宣该项目前需要做的

### ISSUE THREAD

**Issue by xen0n** [loongson-community/areweloongyet#4]
* [x] Need to write [a custom plugin](https://docusaurus.io/docs/api/plugin-methods) to have dynamic routes & pages generated from project data: #5
    - [x] Move data definition from TS to separate user-friendly files (special Markdown files? YAML files?): YAML, #5
* [ ] Styling!!!
    - [x] Vendor the headline fonts: #3
    - [ ] Homepage: #3 #5, still incomplete
    - [x] Project detail page
* [x] Re-purpose the `blog` directory, replace with a guide to this site

**Comment by xen0n** [comment]
Additional TODOs

* [ ] Mention [the Fedora port](https://mirrors.wsyu.edu.cn/fedora/) in data
* [ ] Somehow migrate [this unofficially compiled timeline of events](https://bbs.loongarch.org/d/15) to this site
* [ ] Investigate interop with https://github.com/loongson-community/micronews

**Comment by xen0n** [comment]
Apparently these unfinished bits are indeed low-priority... closing this issue for now; those tasks shall be tracked individually in new issues.
